name: test_workflow

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17  

    - name: Run Unit Tests - Go 1.17
      run: go test ./...

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18  

    - name: Run Unit Tests - Go 1.18
      run: go test ./...

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19  

    - name: Run Unit Tests - Go 1.19
      run: go test ./...
